name: Run backtest (manual)

on:
  workflow_dispatch:

# ✅ allow the workflow to push commits
permissions:
  contents: write

jobs:
  backtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy matplotlib

      - name: Run backtest
        run: python scripts/backtest.py

      - name: Commit results
        run: |
          set -e
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          # use token-authenticated remote
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          git add public/backtest/*
          if ! git diff --cached --quiet; then
            git commit -m "chore: update backtest results $(date -u +%Y-%m-%dT%H:%M:%SZ)"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit"
          fi
