name: Daily stock picks

# Allow this workflow to push commits (write the JSON file)
permissions:
  contents: write

on:
  schedule:
    - cron: "30 3 * * *"   # Runs daily ~09:00 AM IST
  workflow_dispatch:        # Lets you run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas

      - name: Generate picks JSON
        run: python scripts/pick_stocks.py

      - name: Commit data (public/data/latest.json)
        run: |
          set -e
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          # ensure remote uses the GITHUB_TOKEN
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          # stage the generated file
          git add public/data/latest.json || true

          # commit only if something changed
          if ! git diff --cached --quiet; then
            git commit -m "chore: update daily picks $(date -u +%Y-%m-%dT%H:%M:%SZ)"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit"
          fi
